name: android-apk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Node (for Monaco download)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download Monaco Editor and copy assets
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i monaco-editor@0.52.0
          mkdir -p app/src/main/assets
          rm -rf app/src/main/assets/vs
          cp -r node_modules/monaco-editor/min/vs app/src/main/assets/

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Ensure Gradle Wrapper exists (fallback)
        run: |
          if [ ! -f gradlew ]; then
            echo "Gradle wrapper not found. Installing Gradle via SDKMAN to generate it..."
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
